### ISSUE TITLE
Loading next/previous set of paginated river items

### ISSUE THREAD

**Issue by blacktooth** [blacktooth/elgg-ajaxify#17]

**Comment by ewinslow** [comment]
I wasn't able to get this to work on Chrome.  Seems like the selector needs to be changed to ".elgg-pagination a" perhaps?

**Comment by blacktooth** [comment]
It works for me on Chrome. But I think its better to change it to ".elgg-pagination a" as it will be specific and prevents triggering of event for clicked item (The anchor tag is removed) when it is clicked again.

**Comment by blacktooth** [comment]
Please reopen if you have any problems with it

**Comment by ewinslow** [comment]
OK -- I'm still having trouble so since you are saying it works then it must be something else about my install... I'm getting some strange errors -- I'll see what upgrading Elgg does. Should I be using your custom version of Elgg in order to test your plugin?

**Comment by ewinslow** [comment]
Just upgraded Elgg to latest master, but it's still refreshing the page when I click on a pagination link.
