### ISSUE TITLE
Notifying users when message, comment, post on a discussion appears.

### ISSUE THREAD

**Issue by blacktooth** [blacktooth/elgg-ajaxify#29]

**Comment by ewinslow** [comment]
I don't know that Elgg has any in-site notifications except for just using the messages system, and creating such a plugin is certainly out of scope for this project, so don't worry about that.  That said, automatically updating the messages unread counter when a new message arrives would be legit, but still may be out of scope...

**Comment by blacktooth** [comment]
It is out of scope of my project
