### ISSUE TITLE
Enhance overall responsiveness of ajax features

### ISSUE THREAD

**Issue by ewinslow** [blacktooth/elgg-ajaxify#41]
E.g., Right now I'm seeing significant delays b/w pressing the "like" button and getting page updates.

One approach would be to update the view on submitting the action, and undo those updates if there was an error.

Check out how facebook behaves:
1. Log in and open two windows in a single browser
2. Log out in one window 
3. Try to "like" something in the other window
Notice that the like option updates to "unlike" immediately, but then gets reverted once the server responds that there was a problem saving the action.  This makes the site feel very snappy in the common case (where the action ends up being successful).

**Comment by blacktooth** [comment]
We are using this kind of approach for likes and #15. I have checked for other potential areas but couldn't find any. Can you suggest any other areas?

**Comment by ewinslow** [comment]
deleting comments?

**Comment by blacktooth** [comment]
Forgot to mention about it, I used the same approach for that too!

**Comment by blacktooth** [comment]
We are using this approach at all possible areas.
