### ISSUE TITLE
Getting two success messages when liking something

### ISSUE THREAD

**Issue by ewinslow** [blacktooth/elgg-ajaxify#42]
"You like this item"
"You like this item"

in the upper right corner

**Comment by blacktooth** [comment]
Yeah. The system messages is triggered by both elgg.action and $(document).ajaxSuccess 
Since ajaxSuccess is called for every successful ajax request, I feel the system messages function call can be removed from elgg.action

**Comment by ewinslow** [comment]
Sounds good to me

**Comment by blacktooth** [comment]
Do I have to open a ticket on the trac regarding this?

**Comment by ewinslow** [comment]
Yes -- open a trac ticket

**Comment by ewinslow** [comment]
I think we can call this issue closed because once the trac ticket is addressed, this issue will go away.
