### ISSUE TITLE
Autocomplete search results

### ISSUE THREAD

**Issue by ewinslow** [blacktooth/elgg-ajaxify#44]
Would be nice to have some results pop down as the user is typing to help them see if they're on the right track.

**Comment by blacktooth** [comment]
Isn't this same as #21?

**Comment by ewinslow** [comment]
I was taking "suggestions" to imply a "did you mean ..." kind of result.  This ticket is just about returning the actual results of the current search via ajax.

**Comment by blacktooth** [comment]
Requires commits from https://github.com/blacktooth/Elgg/commits/livesearch to be merged for this to work!
